service:
  name: github-organization-jwt

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-1
  memorySize: 256
  environment:
    GITHUB_CLIENT_ID: ${env:GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${env:GITHUB_CLIENT_SECRET}
    JWT_PRIVATE_KEY: ${env:JWT_PRIVATE_KEY}
    JWT_PUBLIC_KEY: ${env:JWT_PUBLIC_KEY}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  handler:
    handler: bin/handler
    events:
      - http:
          path: authorize
          method: get
      - http:
          path: authorize/callback
          method: get
      - http:
          path: refresh
          method: post
      - http:
          path: public.pem
          method: get
